name: Run Examples

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: 
      - main
      - update_structure  # only for testing
    paths:
      - 'src/**'
      - 'examples/src/**'
      - 'examples/Project.toml'
      - '.github/workflows/Example.yml'
      - 'Project.toml'
  
jobs:
  sync-files:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        julia-version: ['1.6']
        julia-arch: [x64]
        os: [windows-latest, ubuntu-latest]
        experimental: [false]

    steps:
      - name: "Check out repository"
        uses: actions/checkout@v3
        # with:
        #   ref: ${{ github.ref }}

      - name: "Set up Julia"
        uses: julia-actions/setup-julia@v1
        with:
            version: ${{ matrix.julia-version }}
            arch: ${{ matrix.julia-arch }}

      - name: "Install dependencies"
        run: julia --project=examples/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'

      - name: "Install packages"
        run: pip install jupyter nbconvert
                        
      - name: "Execute and synchronize all files"
        run: |
          jupyter nbconvert --ExecutePreprocessor.kernel_name="julia-1.6" --to notebook --inplace --execute ./examples/src/*.ipynb
          jupyter nbconvert --to script ./examples/src/*.ipynb
          jupyter nbconvert --to markdown ./examples/src/*.ipynb
      
      - name: "Auto commit"
        if: ${{ matrix.os == 'ubuntu-latest'}}
        env: 
          CI_COMMIT_MESSAGE: Jupyter nbconvert synch - modified, paired .ipynb files
          CI_COMMIT_AUTHOR: github-actions[bot]
        run: |
          git fetch origin examples
          git stash
          git checkout examples
          git stash apply
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "${{ env.CI_COMMIT_AUTHOR }}@users.noreply.github.com"
          git config --global core.autocrlf false
          git add examples/src/
          git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
          git push origin HEAD:examples  

  call-docu:
    needs: sync-files
    uses: ./.github/workflows/Documentation.yml
    secrets: inherit