name: Run Examples

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: 
      - main
    paths:
      - 'src/**'
      - 'examples/src/**'
      - 'examples/Project.toml'
      - '.github/Example.yml'
      - 'Project.toml'
  
jobs:
  sync-files:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        julia-version: ['1.6']
        julia-arch: [x64]
        os: [windows-latest, ubuntu-latest]
        experimental: [false]

    steps:
      - name: "Check out repository"
        uses: actions/checkout@v3

      - name: "Set up Julia"
        uses: julia-actions/setup-julia@v1
        with:
            version: ${{ matrix.julia-version }}
            arch: ${{ matrix.julia-arch }}

      - name: "Build package"
        uses: julia-actions/julia-buildpkg@v1

      - name: "Install packages"
        run: pip install jupyter nbconvert

      - name: "Set path filter"
        uses: dorny/paths-filter@v2
        id: filter
        with:
          list-files: shell
          filters: |
            all:
              - 'examples/src/**.ipynb'
                        
      - name: "Execute and synchronize all files"
        run: |
          jupyter nbconvert --ExecutePreprocessor.kernel_name="julia-1.6" --to notebook --inplace --execute ${{ steps.filter.outputs.all_files }}
          jupyter nbconvert --to script ${{ steps.filter.outputs.all_files }}
          jupyter nbconvert --to markdown ${{ steps.filter.outputs.all_files }}
      
      - name: "Auto commit"
        if: ${{ matrix.os == 'ubuntu-latest'}}
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Jupyter nbconvert synch - modified, paired .ipynb files
          push_options: '--force-with-lease'
          branch: examples
          file_pattern: 'examples/src/*'

  call-docu:
    needs: sync-files
    uses: ./.github/workflows/Dokumentation.yml@main
    secrets: inherit